modLoader="javafml"
loaderVersion="[41,)"
license="The Apache License, Version 2.0"

[[mods]]
modId="dupkeys"
version="${file.jarVersion}"
displayName="Dupkeys"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dupkeys"
updateJSONURL="https://assets.melanx.de/updates/dupkeys.json"
authors="noeppi_noeppi"
description="""
Virtual Keys
"""

[[dependencies.dupkeys]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.33,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.dupkeys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.dupkeys]]
    modId="libx"
    mandatory=true
    versionRange="[1.19-4.0.7,)"
    ordering="NONE"
    side="CLIENT"
