modLoader="javafml"
loaderVersion="[47,)"
license="The Apache License, Version 2.0"

[[mods]]
modId="dupkeys"
version="${version}"
displayName="Dupkeys"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dupkeys"
updateJSONURL="https://assets.melanx.de/updates/dupkeys.json"
authors="noeppi_noeppi"
description="""
Virtual Keys
"""

[[dependencies.dupkeys]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.3,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.dupkeys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.dupkeys]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.1,)"
    ordering="NONE"
    side="CLIENT"
