modLoader="javafml"
loaderVersion="[40,)"
license="The Apache License, Version 2.0"

[[mods]]
modId="dupkeys"
version="${file.jarVersion}"
displayName="Dupkeys"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dupkeys"
updateJSONURL="https://assets.melanx.de/updates/dupkeys.json"
authors="noeppi_noeppi"
description="""
Virtual Keys
"""

[[dependencies.dupkeys]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.13,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.dupkeys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.dupkeys]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.2,)"
    ordering="NONE"
    side="CLIENT"
